@startuml

!include config.puml

(Good Tools) as FT
(Productive Developers) as PD
(More Tests) as MT
(Higher Quality) as HQ
(More Features) as MF
(Better Product) as BP
(Happy Developers) as HD
(Happy Customers) as HC

FT --> PD
FT --> MT
MT --> HQ
PD --> MF
HQ --> BP
MF --> BP
BP --> HC
BP --> HD

@enduml
